---
- hosts: localhost
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name:
          - python3-pip
          - python3-venv
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - qemu-kvm
        state: present
        update_cache: yes

    - name: Install GNS3 via pip
      pip:
        name: gns3-server
        executable: pip3

    - name: Create GNS3 config directory
      file:
        path: /etc/gns3
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create GNS3 server config file
      copy:
        dest: /etc/gns3/gns3_server.conf
        content: |
          [Server]
          host = 0.0.0.0
          port = 3080
          images_path = /opt/gns3/images
          projects_path = /opt/gns3/projects
      owner: ubuntu
      group: ubuntu
      mode: '0644'

    - name: Enable and start GNS3 service
      systemd:
        name: gns3
        enabled: yes
        state: started
