---
- hosts: all
  become: true
  tasks:

    - name: Ensure prerequisites are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3
        - python3-pip
        - python3-venv
        - git
        - curl

    - name: Ensure /opt/gns3 exists with correct permissions
      file:
        path: /opt/gns3
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Install GNS3 server via pip
      pip:
        name: gns3-server
        state: latest

    - name: Create GNS3 config directory
      file:
        path: /etc/gns3
        state: directory
        mode: '0755'

    - name: Deploy GNS3 server config
      copy:
        dest: /etc/gns3/gns3_server.conf
        content: |
          [Server]
          host = 0.0.0.0
          port = 3080
          images_path = /opt/gns3/images
          projects_path = /opt/gns3/projects
          appliances_path = /opt/gns3/appliances

    - name: Deploy systemd unit file for gns3
      copy:
        dest: /etc/systemd/system/gns3.service
        content: |
          [Unit]
          Description=GNS3 server
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /usr/local/bin/gns3server --config /etc/gns3/gns3_server.conf
          Restart=always
          User=ubuntu
          WorkingDirectory=/home/ubuntu

          [Install]
          WantedBy=multi-user.target
      notify: Restart gns3

  handlers:
    - name: Restart gns3
      systemd:
        name: gns3
        state: restarted
        enabled: yes
